<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsProductImage extends \EasyShop\Entities\EsProductImage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'idProductImage', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'productImagePath', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'productImageType', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'isPrimary', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'product');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'idProductImage', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'productImagePath', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'productImageType', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'isPrimary', '' . "\0" . 'EasyShop\\Entities\\EsProductImage' . "\0" . 'product');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsProductImage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProductImage()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProductImage();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProductImage', array());

        return parent::getIdProductImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductImagePath($productImagePath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductImagePath', array($productImagePath));

        return parent::setProductImagePath($productImagePath);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductImagePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductImagePath', array());

        return parent::getProductImagePath();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductImageType($productImageType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductImageType', array($productImageType));

        return parent::setProductImageType($productImageType);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductImageType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductImageType', array());

        return parent::getProductImageType();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPrimary($isPrimary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPrimary', array($isPrimary));

        return parent::setIsPrimary($isPrimary);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPrimary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPrimary', array());

        return parent::getIsPrimary();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\EasyShop\Entities\EsProduct $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

}
