<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsPaymentBankdeposit extends \EasyShop\Entities\EsPaymentBankdeposit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'idPaymentBankdeposit', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'bank', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'refNum', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'amount', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'dateDeposit', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'comment', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'datemodified', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'isInvalid', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'order');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'idPaymentBankdeposit', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'bank', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'refNum', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'amount', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'dateDeposit', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'comment', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'datemodified', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'isInvalid', '' . "\0" . 'EasyShop\\Entities\\EsPaymentBankdeposit' . "\0" . 'order');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsPaymentBankdeposit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPaymentBankdeposit()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPaymentBankdeposit();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPaymentBankdeposit', array());

        return parent::getIdPaymentBankdeposit();
    }

    /**
     * {@inheritDoc}
     */
    public function setBank($bank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBank', array($bank));

        return parent::setBank($bank);
    }

    /**
     * {@inheritDoc}
     */
    public function getBank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBank', array());

        return parent::getBank();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefNum($refNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefNum', array($refNum));

        return parent::setRefNum($refNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefNum', array());

        return parent::getRefNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', array($amount));

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', array());

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeposit($dateDeposit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeposit', array($dateDeposit));

        return parent::setDateDeposit($dateDeposit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeposit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeposit', array());

        return parent::getDateDeposit();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', array($comment));

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', array());

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodified($datemodified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodified', array($datemodified));

        return parent::setDatemodified($datemodified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemodified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemodified', array());

        return parent::getDatemodified();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsInvalid($isInvalid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsInvalid', array($isInvalid));

        return parent::setIsInvalid($isInvalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsInvalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsInvalid', array());

        return parent::getIsInvalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\EasyShop\Entities\EsOrder $order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', array($order));

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', array());

        return parent::getOrder();
    }

}
