<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsMember extends \EasyShop\Entities\EsMember implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'idMember', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'username', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'usersession', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'password', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'contactno', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'isContactnoVerify', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'email', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'isEmailVerify', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'gender', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'birthday', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'datecreated', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'lastmodifieddate', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'lastLoginDatetime', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'lastLoginIp', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'loginCount', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'fullname', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'nickname', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'imgurl', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'userdata', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'remarks', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'isAdmin', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'storeDesc', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'isPromoValid', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'slug', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'session');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'idMember', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'username', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'usersession', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'password', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'contactno', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'isContactnoVerify', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'email', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'isEmailVerify', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'gender', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'birthday', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'datecreated', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'lastmodifieddate', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'lastLoginDatetime', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'lastLoginIp', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'loginCount', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'fullname', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'nickname', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'imgurl', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'userdata', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'remarks', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'isAdmin', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'storeDesc', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'isPromoValid', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'slug', '' . "\0" . 'EasyShop\\Entities\\EsMember' . "\0" . 'session');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsMember $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdMember()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdMember();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMember', array());

        return parent::getIdMember();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsersession($usersession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsersession', array($usersession));

        return parent::setUsersession($usersession);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersession', array());

        return parent::getUsersession();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactno($contactno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactno', array($contactno));

        return parent::setContactno($contactno);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactno', array());

        return parent::getContactno();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsContactnoVerify($isContactnoVerify)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsContactnoVerify', array($isContactnoVerify));

        return parent::setIsContactnoVerify($isContactnoVerify);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsContactnoVerify()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsContactnoVerify', array());

        return parent::getIsContactnoVerify();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEmailVerify($isEmailVerify)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEmailVerify', array($isEmailVerify));

        return parent::setIsEmailVerify($isEmailVerify);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEmailVerify()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEmailVerify', array());

        return parent::getIsEmailVerify();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', array($birthday));

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', array());

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreated($datecreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreated', array($datecreated));

        return parent::setDatecreated($datecreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreated', array());

        return parent::getDatecreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastmodifieddate($lastmodifieddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastmodifieddate', array($lastmodifieddate));

        return parent::setLastmodifieddate($lastmodifieddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastmodifieddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastmodifieddate', array());

        return parent::getLastmodifieddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLoginDatetime($lastLoginDatetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLoginDatetime', array($lastLoginDatetime));

        return parent::setLastLoginDatetime($lastLoginDatetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLoginDatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLoginDatetime', array());

        return parent::getLastLoginDatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLoginIp($lastLoginIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLoginIp', array($lastLoginIp));

        return parent::setLastLoginIp($lastLoginIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLoginIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLoginIp', array());

        return parent::getLastLoginIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginCount($loginCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginCount', array($loginCount));

        return parent::setLoginCount($loginCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginCount', array());

        return parent::getLoginCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullname($fullname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullname', array($fullname));

        return parent::setFullname($fullname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullname', array());

        return parent::getFullname();
    }

    /**
     * {@inheritDoc}
     */
    public function setNickname($nickname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNickname', array($nickname));

        return parent::setNickname($nickname);
    }

    /**
     * {@inheritDoc}
     */
    public function getNickname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNickname', array());

        return parent::getNickname();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgurl($imgurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgurl', array($imgurl));

        return parent::setImgurl($imgurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgurl', array());

        return parent::getImgurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserdata($userdata)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserdata', array($userdata));

        return parent::setUserdata($userdata);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserdata()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserdata', array());

        return parent::getUserdata();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemarks($remarks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemarks', array($remarks));

        return parent::setRemarks($remarks);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemarks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemarks', array());

        return parent::getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsAdmin($isAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsAdmin', array($isAdmin));

        return parent::setIsAdmin($isAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsAdmin', array());

        return parent::getIsAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setStoreDesc($storeDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStoreDesc', array($storeDesc));

        return parent::setStoreDesc($storeDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getStoreDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoreDesc', array());

        return parent::getStoreDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPromoValid($isPromoValid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPromoValid', array($isPromoValid));

        return parent::setIsPromoValid($isPromoValid);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPromoValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPromoValid', array());

        return parent::getIsPromoValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function addSession(\EasyShop\Entities\CiSessions $session)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSession', array($session));

        return parent::addSession($session);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSession(\EasyShop\Entities\CiSessions $session)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSession', array($session));

        return parent::removeSession($session);
    }

    /**
     * {@inheritDoc}
     */
    public function getSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSession', array());

        return parent::getSession();
    }

}
