<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsOrderProduct extends \EasyShop\Entities\EsOrderProduct implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'idOrderProduct', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'orderQuantity', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'price', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'handlingFee', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'total', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'productItemId', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'buyerBillingId', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'isReject', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'easyshopCharge', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'paymentMethodCharge', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'net', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'sellerBillingId', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'seller', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'order', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'status', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'product');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'idOrderProduct', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'orderQuantity', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'price', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'handlingFee', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'total', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'productItemId', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'buyerBillingId', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'isReject', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'easyshopCharge', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'paymentMethodCharge', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'net', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'sellerBillingId', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'seller', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'order', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'status', '' . "\0" . 'EasyShop\\Entities\\EsOrderProduct' . "\0" . 'product');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsOrderProduct $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOrderProduct()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOrderProduct();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrderProduct', array());

        return parent::getIdOrderProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderQuantity($orderQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderQuantity', array($orderQuantity));

        return parent::setOrderQuantity($orderQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderQuantity', array());

        return parent::getOrderQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setHandlingFee($handlingFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHandlingFee', array($handlingFee));

        return parent::setHandlingFee($handlingFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getHandlingFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandlingFee', array());

        return parent::getHandlingFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductItemId($productItemId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductItemId', array($productItemId));

        return parent::setProductItemId($productItemId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductItemId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductItemId', array());

        return parent::getProductItemId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyerBillingId($buyerBillingId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyerBillingId', array($buyerBillingId));

        return parent::setBuyerBillingId($buyerBillingId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyerBillingId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyerBillingId', array());

        return parent::getBuyerBillingId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsReject($isReject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsReject', array($isReject));

        return parent::setIsReject($isReject);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsReject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsReject', array());

        return parent::getIsReject();
    }

    /**
     * {@inheritDoc}
     */
    public function setEasyshopCharge($easyshopCharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEasyshopCharge', array($easyshopCharge));

        return parent::setEasyshopCharge($easyshopCharge);
    }

    /**
     * {@inheritDoc}
     */
    public function getEasyshopCharge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEasyshopCharge', array());

        return parent::getEasyshopCharge();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethodCharge($paymentMethodCharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethodCharge', array($paymentMethodCharge));

        return parent::setPaymentMethodCharge($paymentMethodCharge);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethodCharge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethodCharge', array());

        return parent::getPaymentMethodCharge();
    }

    /**
     * {@inheritDoc}
     */
    public function setNet($net)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNet', array($net));

        return parent::setNet($net);
    }

    /**
     * {@inheritDoc}
     */
    public function getNet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNet', array());

        return parent::getNet();
    }

    /**
     * {@inheritDoc}
     */
    public function setSellerBillingId($sellerBillingId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSellerBillingId', array($sellerBillingId));

        return parent::setSellerBillingId($sellerBillingId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellerBillingId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellerBillingId', array());

        return parent::getSellerBillingId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeller(\EasyShop\Entities\EsMember $seller = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeller', array($seller));

        return parent::setSeller($seller);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeller()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeller', array());

        return parent::getSeller();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\EasyShop\Entities\EsOrder $order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', array($order));

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', array());

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\EasyShop\Entities\EsOrderProductStatus $status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\EasyShop\Entities\EsProduct $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

}
