<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsOrderProductHistory extends \EasyShop\Entities\EsOrderProductHistory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'idOrderProductHistory', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'comment', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'dateAdded', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'orderProduct', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'orderProductStatus');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'idOrderProductHistory', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'comment', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'dateAdded', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'orderProduct', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductHistory' . "\0" . 'orderProductStatus');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsOrderProductHistory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOrderProductHistory()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOrderProductHistory();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrderProductHistory', array());

        return parent::getIdOrderProductHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', array($comment));

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', array());

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdded($dateAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdded', array($dateAdded));

        return parent::setDateAdded($dateAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdded', array());

        return parent::getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderProduct(\EasyShop\Entities\EsOrderProduct $orderProduct = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderProduct', array($orderProduct));

        return parent::setOrderProduct($orderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderProduct', array());

        return parent::getOrderProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderProductStatus(\EasyShop\Entities\EsOrderProductStatus $orderProductStatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderProductStatus', array($orderProductStatus));

        return parent::setOrderProductStatus($orderProductStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderProductStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderProductStatus', array());

        return parent::getOrderProductStatus();
    }

}
