<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsOrderShippingAddress extends \EasyShop\Entities\EsOrderShippingAddress implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'idOrderShippingAddress', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'address', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'consignee', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'mobile', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'telephone', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'lat', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'lng', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'city', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'country', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'stateregion');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'idOrderShippingAddress', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'address', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'consignee', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'mobile', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'telephone', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'lat', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'lng', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'city', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'country', '' . "\0" . 'EasyShop\\Entities\\EsOrderShippingAddress' . "\0" . 'stateregion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsOrderShippingAddress $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOrderShippingAddress()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOrderShippingAddress();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrderShippingAddress', array());

        return parent::getIdOrderShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsignee($consignee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsignee', array($consignee));

        return parent::setConsignee($consignee);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsignee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsignee', array());

        return parent::getConsignee();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setLat($lat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLat', array($lat));

        return parent::setLat($lat);
    }

    /**
     * {@inheritDoc}
     */
    public function getLat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLat', array());

        return parent::getLat();
    }

    /**
     * {@inheritDoc}
     */
    public function setLng($lng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLng', array($lng));

        return parent::setLng($lng);
    }

    /**
     * {@inheritDoc}
     */
    public function getLng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLng', array());

        return parent::getLng();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(\EasyShop\Entities\EsLocationLookup $city = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\EasyShop\Entities\EsLocationLookup $country = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setStateregion(\EasyShop\Entities\EsLocationLookup $stateregion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStateregion', array($stateregion));

        return parent::setStateregion($stateregion);
    }

    /**
     * {@inheritDoc}
     */
    public function getStateregion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStateregion', array());

        return parent::getStateregion();
    }

}
