<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsVerifcode extends \EasyShop\Entities\EsVerifcode implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'idVerifcode', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'emailcode', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'mobilecode', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'date', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'emailcount', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'mobilecount', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'fpTimestamp', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'fpCode', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'member');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'idVerifcode', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'emailcode', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'mobilecode', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'date', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'emailcount', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'mobilecount', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'fpTimestamp', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'fpCode', '' . "\0" . 'EasyShop\\Entities\\EsVerifcode' . "\0" . 'member');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsVerifcode $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdVerifcode()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdVerifcode();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVerifcode', array());

        return parent::getIdVerifcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailcode($emailcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailcode', array($emailcode));

        return parent::setEmailcode($emailcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailcode', array());

        return parent::getEmailcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobilecode($mobilecode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobilecode', array($mobilecode));

        return parent::setMobilecode($mobilecode);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobilecode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobilecode', array());

        return parent::getMobilecode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailcount($emailcount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailcount', array($emailcount));

        return parent::setEmailcount($emailcount);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailcount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailcount', array());

        return parent::getEmailcount();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobilecount($mobilecount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobilecount', array($mobilecount));

        return parent::setMobilecount($mobilecount);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobilecount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobilecount', array());

        return parent::getMobilecount();
    }

    /**
     * {@inheritDoc}
     */
    public function setFpTimestamp($fpTimestamp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFpTimestamp', array($fpTimestamp));

        return parent::setFpTimestamp($fpTimestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getFpTimestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFpTimestamp', array());

        return parent::getFpTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setFpCode($fpCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFpCode', array($fpCode));

        return parent::setFpCode($fpCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getFpCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFpCode', array());

        return parent::getFpCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMember(\EasyShop\Entities\EsMember $member = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMember', array($member));

        return parent::setMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMember', array());

        return parent::getMember();
    }

}
