<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsOrderProductAttr extends \EasyShop\Entities\EsOrderProductAttr implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'idOrderOption', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'attrName', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'attrValue', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'attrPrice', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'orderProduct');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'idOrderOption', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'attrName', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'attrValue', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'attrPrice', '' . "\0" . 'EasyShop\\Entities\\EsOrderProductAttr' . "\0" . 'orderProduct');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsOrderProductAttr $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOrderOption()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOrderOption();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrderOption', array());

        return parent::getIdOrderOption();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttrName($attrName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttrName', array($attrName));

        return parent::setAttrName($attrName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttrName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttrName', array());

        return parent::getAttrName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttrValue($attrValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttrValue', array($attrValue));

        return parent::setAttrValue($attrValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttrValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttrValue', array());

        return parent::getAttrValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttrPrice($attrPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttrPrice', array($attrPrice));

        return parent::setAttrPrice($attrPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttrPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttrPrice', array());

        return parent::getAttrPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderProduct(\EasyShop\Entities\EsOrderProduct $orderProduct = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderProduct', array($orderProduct));

        return parent::setOrderProduct($orderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderProduct', array());

        return parent::getOrderProduct();
    }

}
