<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsAttr extends \EasyShop\Entities\EsAttr implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'idAttr', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'name', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'attrLookuplist', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'cat', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'datatype');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'idAttr', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'name', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'attrLookuplist', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'cat', '' . "\0" . 'EasyShop\\Entities\\EsAttr' . "\0" . 'datatype');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsAttr $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdAttr()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAttr();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAttr', array());

        return parent::getIdAttr();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttrLookuplist(\EasyShop\Entities\EsAttrLookuplist $attrLookuplist = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttrLookuplist', array($attrLookuplist));

        return parent::setAttrLookuplist($attrLookuplist);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttrLookuplist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttrLookuplist', array());

        return parent::getAttrLookuplist();
    }

    /**
     * {@inheritDoc}
     */
    public function setCat(\EasyShop\Entities\EsCat $cat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCat', array($cat));

        return parent::setCat($cat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCat', array());

        return parent::getCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatatype(\EasyShop\Entities\EsDatatype $datatype = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatatype', array($datatype));

        return parent::setDatatype($datatype);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatatype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatatype', array());

        return parent::getDatatype();
    }

}
