<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsBillingInfo extends \EasyShop\Entities\EsBillingInfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'idBillingInfo', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'paymentType', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'userAccount', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'bankId', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'bankAccountName', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'bankAccountNumber', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'isDefault', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'dateadded', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'datemodified', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'isDelete', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'member');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'idBillingInfo', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'paymentType', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'userAccount', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'bankId', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'bankAccountName', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'bankAccountNumber', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'isDefault', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'dateadded', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'datemodified', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'isDelete', '' . "\0" . 'EasyShop\\Entities\\EsBillingInfo' . "\0" . 'member');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsBillingInfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdBillingInfo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdBillingInfo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBillingInfo', array());

        return parent::getIdBillingInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentType($paymentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', array($paymentType));

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', array());

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAccount($userAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAccount', array($userAccount));

        return parent::setUserAccount($userAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAccount', array());

        return parent::getUserAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankId($bankId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankId', array($bankId));

        return parent::setBankId($bankId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankId', array());

        return parent::getBankId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankAccountName($bankAccountName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankAccountName', array($bankAccountName));

        return parent::setBankAccountName($bankAccountName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankAccountName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankAccountName', array());

        return parent::getBankAccountName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankAccountNumber($bankAccountNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankAccountNumber', array($bankAccountNumber));

        return parent::setBankAccountNumber($bankAccountNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankAccountNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankAccountNumber', array());

        return parent::getBankAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDefault($isDefault)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDefault', array($isDefault));

        return parent::setIsDefault($isDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDefault()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDefault', array());

        return parent::getIsDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateadded($dateadded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateadded', array($dateadded));

        return parent::setDateadded($dateadded);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateadded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateadded', array());

        return parent::getDateadded();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodified($datemodified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodified', array($datemodified));

        return parent::setDatemodified($datemodified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemodified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemodified', array());

        return parent::getDatemodified();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDelete($isDelete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDelete', array($isDelete));

        return parent::setIsDelete($isDelete);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDelete', array());

        return parent::getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setMember(\EasyShop\Entities\EsMember $member = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMember', array($member));

        return parent::setMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMember', array());

        return parent::getMember();
    }

}
