<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsProductReview extends \EasyShop\Entities\EsProductReview implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'idReview', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'pReviewid', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'datesubmitted', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'rating', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'title', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'review', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'isShow', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'datehidden', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'member', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'product');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'idReview', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'pReviewid', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'datesubmitted', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'rating', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'title', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'review', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'isShow', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'datehidden', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'member', '' . "\0" . 'EasyShop\\Entities\\EsProductReview' . "\0" . 'product');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsProductReview $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdReview()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdReview();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdReview', array());

        return parent::getIdReview();
    }

    /**
     * {@inheritDoc}
     */
    public function setPReviewid($pReviewid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPReviewid', array($pReviewid));

        return parent::setPReviewid($pReviewid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPReviewid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPReviewid', array());

        return parent::getPReviewid();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatesubmitted($datesubmitted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatesubmitted', array($datesubmitted));

        return parent::setDatesubmitted($datesubmitted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatesubmitted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatesubmitted', array());

        return parent::getDatesubmitted();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', array($rating));

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', array());

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setReview($review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReview', array($review));

        return parent::setReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function getReview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReview', array());

        return parent::getReview();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsShow($isShow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsShow', array($isShow));

        return parent::setIsShow($isShow);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsShow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsShow', array());

        return parent::getIsShow();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatehidden($datehidden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatehidden', array($datehidden));

        return parent::setDatehidden($datehidden);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatehidden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatehidden', array());

        return parent::getDatehidden();
    }

    /**
     * {@inheritDoc}
     */
    public function setMember(\EasyShop\Entities\EsMember $member = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMember', array($member));

        return parent::setMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMember', array());

        return parent::getMember();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\EasyShop\Entities\EsProduct $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

}
