<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsProductShippingComment extends \EasyShop\Entities\EsProductShippingComment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'idShippingComment', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'courier', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'trackingNum', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'comment', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'expectedDate', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'datemodified', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'deliveryDate', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'orderProduct', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'member');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'idShippingComment', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'courier', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'trackingNum', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'comment', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'expectedDate', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'datemodified', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'deliveryDate', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'orderProduct', '' . "\0" . 'EasyShop\\Entities\\EsProductShippingComment' . "\0" . 'member');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsProductShippingComment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdShippingComment()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdShippingComment();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdShippingComment', array());

        return parent::getIdShippingComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourier($courier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourier', array($courier));

        return parent::setCourier($courier);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourier', array());

        return parent::getCourier();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackingNum($trackingNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackingNum', array($trackingNum));

        return parent::setTrackingNum($trackingNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingNum', array());

        return parent::getTrackingNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', array($comment));

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', array());

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpectedDate($expectedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpectedDate', array($expectedDate));

        return parent::setExpectedDate($expectedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpectedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpectedDate', array());

        return parent::getExpectedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodified($datemodified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodified', array($datemodified));

        return parent::setDatemodified($datemodified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemodified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemodified', array());

        return parent::getDatemodified();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryDate($deliveryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryDate', array($deliveryDate));

        return parent::setDeliveryDate($deliveryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryDate', array());

        return parent::getDeliveryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderProduct(\EasyShop\Entities\EsOrderProduct $orderProduct = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderProduct', array($orderProduct));

        return parent::setOrderProduct($orderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderProduct', array());

        return parent::getOrderProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setMember(\EasyShop\Entities\EsMember $member = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMember', array($member));

        return parent::setMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMember', array());

        return parent::getMember();
    }

}
