<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsCat extends \EasyShop\Entities\EsCat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'idCat', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'name', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'description', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'keywords', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'sortOrder', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'isMain', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'design1', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'design2', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'design3', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'slug', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'parent');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'idCat', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'name', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'description', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'keywords', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'sortOrder', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'isMain', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'design1', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'design2', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'design3', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'slug', '' . "\0" . 'EasyShop\\Entities\\EsCat' . "\0" . 'parent');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsCat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCat()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCat();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCat', array());

        return parent::getIdCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywords($keywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywords', array($keywords));

        return parent::setKeywords($keywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', array());

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setSortOrder($sortOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortOrder', array($sortOrder));

        return parent::setSortOrder($sortOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getSortOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortOrder', array());

        return parent::getSortOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMain($isMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMain', array($isMain));

        return parent::setIsMain($isMain);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMain', array());

        return parent::getIsMain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesign1($design1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesign1', array($design1));

        return parent::setDesign1($design1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesign1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesign1', array());

        return parent::getDesign1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesign2($design2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesign2', array($design2));

        return parent::setDesign2($design2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesign2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesign2', array());

        return parent::getDesign2();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesign3($design3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesign3', array($design3));

        return parent::setDesign3($design3);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesign3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesign3', array());

        return parent::getDesign3();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\EasyShop\Entities\EsCat $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

}
