<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsOrder extends \EasyShop\Entities\EsOrder implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'idOrder', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'invoiceNo', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'paymentAddressId', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'shippingAddressId', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'total', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'dateadded', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'datemodified', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'ip', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'dataResponse', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'transactionId', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'easyshopCharge', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'paymentMethodCharge', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'net', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'postbackcount', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'isFlag', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'buyer', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'orderStatus', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'paymentMethod');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'idOrder', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'invoiceNo', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'paymentAddressId', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'shippingAddressId', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'total', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'dateadded', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'datemodified', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'ip', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'dataResponse', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'transactionId', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'easyshopCharge', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'paymentMethodCharge', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'net', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'postbackcount', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'isFlag', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'buyer', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'orderStatus', '' . "\0" . 'EasyShop\\Entities\\EsOrder' . "\0" . 'paymentMethod');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsOrder $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOrder()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOrder();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrder', array());

        return parent::getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceNo($invoiceNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceNo', array($invoiceNo));

        return parent::setInvoiceNo($invoiceNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceNo', array());

        return parent::getInvoiceNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentAddressId($paymentAddressId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentAddressId', array($paymentAddressId));

        return parent::setPaymentAddressId($paymentAddressId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressId', array());

        return parent::getPaymentAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddressId($shippingAddressId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddressId', array($shippingAddressId));

        return parent::setShippingAddressId($shippingAddressId);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddressId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddressId', array());

        return parent::getShippingAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateadded($dateadded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateadded', array($dateadded));

        return parent::setDateadded($dateadded);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateadded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateadded', array());

        return parent::getDateadded();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodified($datemodified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodified', array($datemodified));

        return parent::setDatemodified($datemodified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemodified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemodified', array());

        return parent::getDatemodified();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp($ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', array($ip));

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', array());

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataResponse($dataResponse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataResponse', array($dataResponse));

        return parent::setDataResponse($dataResponse);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataResponse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataResponse', array());

        return parent::getDataResponse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionId($transactionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionId', array($transactionId));

        return parent::setTransactionId($transactionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionId', array());

        return parent::getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEasyshopCharge($easyshopCharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEasyshopCharge', array($easyshopCharge));

        return parent::setEasyshopCharge($easyshopCharge);
    }

    /**
     * {@inheritDoc}
     */
    public function getEasyshopCharge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEasyshopCharge', array());

        return parent::getEasyshopCharge();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethodCharge($paymentMethodCharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethodCharge', array($paymentMethodCharge));

        return parent::setPaymentMethodCharge($paymentMethodCharge);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethodCharge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethodCharge', array());

        return parent::getPaymentMethodCharge();
    }

    /**
     * {@inheritDoc}
     */
    public function setNet($net)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNet', array($net));

        return parent::setNet($net);
    }

    /**
     * {@inheritDoc}
     */
    public function getNet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNet', array());

        return parent::getNet();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostbackcount($postbackcount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostbackcount', array($postbackcount));

        return parent::setPostbackcount($postbackcount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostbackcount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostbackcount', array());

        return parent::getPostbackcount();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFlag($isFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFlag', array($isFlag));

        return parent::setIsFlag($isFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFlag', array());

        return parent::getIsFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyer(\EasyShop\Entities\EsMember $buyer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyer', array($buyer));

        return parent::setBuyer($buyer);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyer', array());

        return parent::getBuyer();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderStatus(\EasyShop\Entities\EsOrderStatus $orderStatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderStatus', array($orderStatus));

        return parent::setOrderStatus($orderStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderStatus', array());

        return parent::getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethod(\EasyShop\Entities\EsPaymentMethod $paymentMethod = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethod', array($paymentMethod));

        return parent::setPaymentMethod($paymentMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethod', array());

        return parent::getPaymentMethod();
    }

}
