<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CiSessions extends \EasyShop\Entities\CiSessions implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'sessionId', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'ipAddress', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'userAgent', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'lastActivity', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'userData', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'oldSessionId', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'member');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'sessionId', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'ipAddress', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'userAgent', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'lastActivity', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'userData', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'oldSessionId', '' . "\0" . 'EasyShop\\Entities\\CiSessions' . "\0" . 'member');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CiSessions $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSessionId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getSessionId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessionId', array());

        return parent::getSessionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpAddress($ipAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpAddress', array($ipAddress));

        return parent::setIpAddress($ipAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpAddress', array());

        return parent::getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAgent($userAgent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAgent', array($userAgent));

        return parent::setUserAgent($userAgent);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAgent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAgent', array());

        return parent::getUserAgent();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastActivity($lastActivity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastActivity', array($lastActivity));

        return parent::setLastActivity($lastActivity);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastActivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastActivity', array());

        return parent::getLastActivity();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserData($userData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserData', array($userData));

        return parent::setUserData($userData);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserData', array());

        return parent::getUserData();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldSessionId($oldSessionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldSessionId', array($oldSessionId));

        return parent::setOldSessionId($oldSessionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldSessionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldSessionId', array());

        return parent::getOldSessionId();
    }

    /**
     * {@inheritDoc}
     */
    public function addMember(\EasyShop\Entities\EsMember $member)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMember', array($member));

        return parent::addMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMember(\EasyShop\Entities\EsMember $member)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMember', array($member));

        return parent::removeMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMember', array());

        return parent::getMember();
    }

}
