<?php

namespace EasyShop\Doctrine\Proxies\__CG__\EasyShop\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EsMemberFeedback extends \EasyShop\Entities\EsMemberFeedback implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'idFeedback', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'feedbMsg', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'feedbKind', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'dateadded', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'rating1', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'rating2', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'rating3', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'member', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'forMemberid', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'order');
        }

        return array('__isInitialized__', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'idFeedback', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'feedbMsg', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'feedbKind', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'dateadded', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'rating1', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'rating2', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'rating3', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'member', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'forMemberid', '' . "\0" . 'EasyShop\\Entities\\EsMemberFeedback' . "\0" . 'order');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EsMemberFeedback $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdFeedback()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdFeedback();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFeedback', array());

        return parent::getIdFeedback();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeedbMsg($feedbMsg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeedbMsg', array($feedbMsg));

        return parent::setFeedbMsg($feedbMsg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeedbMsg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedbMsg', array());

        return parent::getFeedbMsg();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeedbKind($feedbKind)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeedbKind', array($feedbKind));

        return parent::setFeedbKind($feedbKind);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeedbKind()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedbKind', array());

        return parent::getFeedbKind();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateadded($dateadded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateadded', array($dateadded));

        return parent::setDateadded($dateadded);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateadded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateadded', array());

        return parent::getDateadded();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating1($rating1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating1', array($rating1));

        return parent::setRating1($rating1);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating1', array());

        return parent::getRating1();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating2($rating2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating2', array($rating2));

        return parent::setRating2($rating2);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating2', array());

        return parent::getRating2();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating3($rating3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating3', array($rating3));

        return parent::setRating3($rating3);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating3', array());

        return parent::getRating3();
    }

    /**
     * {@inheritDoc}
     */
    public function setMember(\EasyShop\Entities\EsMember $member = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMember', array($member));

        return parent::setMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMember', array());

        return parent::getMember();
    }

    /**
     * {@inheritDoc}
     */
    public function setForMemberid(\EasyShop\Entities\EsMember $forMemberid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForMemberid', array($forMemberid));

        return parent::setForMemberid($forMemberid);
    }

    /**
     * {@inheritDoc}
     */
    public function getForMemberid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForMemberid', array());

        return parent::getForMemberid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\EasyShop\Entities\EsOrder $order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', array($order));

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', array());

        return parent::getOrder();
    }

}
